### ISSUE TITLE
Remove artifact filtering from provider event source servers and add to webhook (Step 2.5)

### ISSUE THREAD

**Issue by grahamia** [sky-uk/kfp-operator#366]
## Overview
currently the provider event source server filters job artifacts using information provided in the run configuration/run resource. This requires the provider to have to have specific KFP Operator knowledge and have access to KFP Operator resources which we don't want. Now we have the webhook within KFP Operator this filtering logic can be moved.

At this point kubeflow provider cant be done until  https://github.com/sky-uk/kfp-operator/issues/318 is fixed.

## Tasks
- [ ] remove the lookup of the run/runconfiguration from the event source server
- [ ] remove the filtering from the event source server
- [ ] pass all required information out (this will require a new struct to hold all information, extending RunCompletionEvent) from the event source server that KFP Operator will require to carry out the filtering, i.e.
    - [ ] task.TaskName
    - [ ] task.GetOutputs() - key from map, ie the name
    - [ ] list of all output artifacts, including uri and metadata (this will need to be serialised out as JSON and then deserialised back into the Struct on the KFP Operator side) for each
- [ ] logic needs to be added to load the run or run configuration within the webhook
- [ ] filter the passed artifacts the same as [provider ESS did](https://github.com/sky-uk/kfp-operator/blob/d3a38b0360fe198a2c2c831851919e6a0ad2e4f7/argo/providers/vai/eventing_server.go#L178)
- [ ] Output correct RunCompletionEvent struct

## Acceptance Criteria
- [ ] provider resources don't need read access to kfp-operator resources (i.e. run and runconfiguration)
- [ ] artifact list passed from provider into KFP Operator webhook should be unfiltered full list with all above information
- [ ] output produced onto the eventbus should now be the correct RunCompletionEvent structure with the filtered list of artifacts.
- [ ] any tests from ESS should be moved/rewritten in KFP Operator.
