### ISSUE TITLE
Manage one-off pipeline runs declaratively

### ISSUE THREAD

**Issue by jmendesky** [sky-uk/kfp-operator#64]
## Overview

We want to support managing Kubeflow Pipelines runs with a new Run resource.

### Technical notes

-  `RunSpec` should be immutable (i.e. re-submission will not be allowed)
- A TTL configuration similar to K8s Job's `ttlSecondsAfterFinished` should allow the run to be deleted after completion
- One-off runs should work for both fixed pipeline versions and latest pipeline versions

### Implementation Notes

The work can be broken up into the following steps
- [x] Run with fixed pipeline versions (ignoring updates) #196 
- [x] Implement a Validating Webhook to make the Spec immutable #202 
- [x] Introduce `CompletionState` to Run's `Status` field #207
  - Depends on #89
- [x] Implement TTL #209
- [x] Allow pipeline reference to be specified without version #210
- [x] Update docs #212
